### ISSUE TITLE
What is DEV_ID?

### ISSUE THREAD

**Issue by vihangatheekshana2006** [Adivise/DisGalaxyX#1]
What is DEV_ID?

/home/runner/DisGalaxyX/node_modules/undici/lib/web/fetch/response.js:528
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/home/runner/DisGalaxyX/node_modules/undici/lib/web/fetch/response.js:528:3)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/DisGalaxyX/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

Node.js v17.9.1
~/DisGalaxyX$

**Comment by Adivise** [comment]
DEV_ID is mean your can use bot only have id in

example DEV_ID: ["123123123", "089700923"]

dont put if you need everyone can use

**Comment by Adivise** [comment]
and try to use this node version https://nodejs.org/dist/v20.11.1/node-v20.11.1-x64.msi
